import "./global.css";

import { ThemeRegistry } from "./components/ThemeRegistry";

import { NavBar } from "./components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <NavBar />
          {children}
        </body>
      </ThemeRegistry>
    </html>
  );
}
